DROP DATABASE AC_BD

CREATE DATABASE AC_BD

CREATE TABLE AC_BD.dbo.PRODUTOS (
                PROD_ID_PK INT IDENTITY (1,1) NOT NULL,
                PROD_NAME VARCHAR(30) ,
                PROD_DESCRICAO VARCHAR(100) ,
                CONSTRAINT PRODUTOS_PK PRIMARY KEY (PROD_ID_PK)
);

INSERT INTO AC_BD.dbo.PRODUTOS (
	PROD_NAME,
	PROD_DESCRICAO
) VALUES (
	'Bolo',
	'Bolo de chocolate'
);