DROP DATABASE AC_BD
CREATE DATABASE AC_BD

CREATE TABLE AC_BD.dbo.PRODUTOS (
                PROD_ID_PK INT IDENTITY (1,1) NOT NULL,
                PROD_NOME VARCHAR(50) ,
                CONSTRAINT PRODUTOS_PK PRIMARY KEY (PROD_ID_PK)
);

create table AC_BD.dbo.CARDAPIOS (
	CARD_ID_PK INT IDENTITY (1,1) NOT NULL,
    CARD_DIA DATE,
    CARD_PROD_ID_FK INT,
    CONSTRAINT CARDAPIO_PK PRIMARY KEY (CARD_ID_PK),
	FOREIGN KEY (CARD_PROD_ID_FK) REFERENCES PRODUTOS(PROD_ID_PK)
	)

INSERT INTO AC_BD.dbo.PRODUTOS (
    PROD_NOME
) VALUES (
	'Bolo de chocolate'
);